### PR TITLE
Add select mechanism

### PR DESCRIPTION
**Pull request by dabuchera**
Added some neat functionalities for selection of a specific option. 
Can be tested with:

```
rl.on('data', (line) => {
  sendMessage(line)
  const hardcodedOptions = ['abcdfe', 'efghij', 'klmnop', 'qrstuv', 'wxyzab', 'cdefgh', 'ijklmn', 'opqrst', 'uvwxyz', 'abcdef']
  if (line === 'options') {
    rl.showOptions(hardcodedOptions)
    return
  }
  rl.prompt()
})
rl.prompt()

rl.on('optionSelected', (selectedOption) => {
  console.log(`Selected option: ${selectedOption}`)
})
```

image

### CODE REVIEW

**Comment by kasperisager** [comment]
Thank you for the suggestion! This is outside the scope of the module, however, and would be best implemented as a separate module.

**Comment by dabuchera** [comment]
Could you set up a repo and i will do a pull request? Maybe call it something like bare-cli-helpers?

**Comment by kasperisager** [comment]
Community modules are more than welcome so feel free to create and publish such a module yourself! There's no need for us to gatekeep it.

**Comment by dabuchera** [comment]
@kasperisager 
https://github.com/dabuchera/bare-select-prompts

Happy for any feedback or PRs

**Pull request closed without merging**
